<MyScreen>
    md_bg_color: app.theme_cls.backgroundColor
    MDLabel:
        markup: True
        padding: (dp(20), 0, 0, 0)
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        text: "Please note that your results did not meet our expectations. Your account has been deactivated. Contact the admin for more information and negotiations!\n\n [b][color=#008080][ref=]Thank you for supporting Embakwe High School[/ref][/color][/b]"
